### ISSUE TITLE
Github action is broken for update upstream

### ISSUE THREAD

**Issue by shivapoudel** [Claudiohbsantos/github-material-icons-extension#20]
@Claudiohbsantos VSCode extension had been released but over this repo action, it is being broken. Can you please look into it?

**Comment by Claudiohbsantos** [comment]
Yeah, just had a chance to take a look. The most immediate problem has just been fixed, I'll babysit it this weekend to make sure it works. Thanks for the heads up

**Comment by Claudiohbsantos** [comment]
Just confirmed it is working now.
