### ISSUE TITLE
Symlink and submodule icons won't show when items match a known extension

### ISSUE THREAD

**Issue by kidonng** [Claudiohbsantos/github-material-icons-extension#27]
Thanks for your efforts in resolving #3! Unfortunately when the items match a known extension:

![image](https://user-images.githubusercontent.com/44045911/139072501-c63f9d8d-86a6-440a-954b-12c4404f3098.png)

(https://github.com/svartalf/rust-battery/tree/master/battery)

...the symlink and submodule icons won't show:

![image](https://user-images.githubusercontent.com/44045911/139072470-1fdd0e38-b173-4b95-a1bf-ea8cc30d9e44.png)

These lines should be hoisted (put in front of the languages matching code):

https://github.com/Claudiohbsantos/github-material-icons-extension/blob/f212d076ac119a027f117e9ab4eee5da528b74ef/src/main.js#L158-L159

**Comment by Claudiohbsantos** [comment]
![chrome_qJysH7hYaD](https://user-images.githubusercontent.com/11323215/140002281-3908f66e-b521-4533-a083-5977fba1e6e5.png)

Fix has been merged. Will be released with next changes soon
