### ISSUE TITLE
Extension crashes in Opera browser

### ISSUE THREAD

**Issue by shahriaarrr** [Claudiohbsantos/github-material-icons-extension#28]
Unfortunately, this extension failed in Opera browser and the icons did not load properly.
![image](https://user-images.githubusercontent.com/75499598/144188437-392fb7fc-56d5-45b2-bf4f-0bafa2ed093a.png)

**Comment by Claudiohbsantos** [comment]
@shahriaarrr Did it use to work before yesterday (Nov 30 2021) ? 

version 1.5.0 started making use of `chrome.runtime` API that is supported by chrome and Firefox but that I imagine might be a little more finicky with cross-browser support

**Comment by shahriaarrr** [comment]
@Claudiohbsantos I installed the new version yesterday and this problem was fixed. Thanks for fixing this bug

**Comment by Claudiohbsantos** [comment]
Awesome, glad to hear that.  Thanks for the report either way!
