### ISSUE TITLE
icon for *.nims  file

### ISSUE THREAD

**Issue by doongjohn** [Claudiohbsantos/github-material-icons-extension#29]
`*.nims` is a [nimscript](https://nim-lang.org/docs/nims.html) file. It can use a same icon as `*.nim` file.

**Comment by Claudiohbsantos** [comment]
Hey @doongjohn . Thanks for the suggestion. I think this would be better handled upstream in the main VSCode extension where we pull icons/mappings from.

I could be mistaken but I think the necessary change would be [here](https://github.com/PKief/vscode-material-icon-theme/blob/251df153f6bcea76efa6a5fa2721cb3c6dce022e/src/icons/fileIcons.ts#L741). I'd suggest opening a PR upstream adding the `.nims` extension support or opening an issue in that repo for discussion.

thanks!
