### ISSUE TITLE
Design flickers on hard reload on GitHub

### ISSUE THREAD

**Issue by shivapoudel** [Claudiohbsantos/github-material-icons-extension#35]
If I tried to hard reload the repository page with cached cleared this kind of design flicker is happening and soon gets disappeared. @Claudiohbsantos can you investigate this I tried but couldn't figure out the culprit styling.

![image](https://user-images.githubusercontent.com/3774827/168727189-735bc2c3-a97d-4571-a893-8158b732d938.png)

**Comment by Claudiohbsantos** [comment]
Hmmm.. Looks like we need to raise the number of icons that are handled synchronously on load. ([see this part of the code](https://github.com/Claudiohbsantos/github-material-icons-extension/blob/master/src/main.js#L22~L41)) No idea what changed to make this necessary. I just [pushed a change](https://github.com/Claudiohbsantos/github-material-icons-extension/commit/0598d68ed8170842bbc0c2171ffab8a7bcb8c14a) that I'm hoping will take care of this (it seems to do locally). 

I'll hold on cutting a new commit while we wrap up the PR that is open. If that is not merged by next weekend I'll try to cut a version including this change so it goes live. 

Thanks for the report!

**Comment by Claudiohbsantos** [comment]
I'm going to close this issue since I believe it is fixed by that commit. Feel free to mention me here if that turns out to not be fixed once this is released
