### ISSUE TITLE
New permissions

### ISSUE THREAD

**Issue by pxladin** [Claudiohbsantos/github-material-icons-extension#39]
![image](https://user-images.githubusercontent.com/31286564/176895204-cce7ecdb-29a9-49d3-9d12-a597e417f55b.png)

What for?

**Comment by eugabrielsilva** [comment]
Aparently the extension now also supports Azure DevOps and BitBucket too: https://github.com/Claudiohbsantos/github-material-icons-extension/pull/31, this requires a new set of permitted websites

Here is a screenshot of bitbucket
![image](https://user-images.githubusercontent.com/64693687/176958316-df9d99c5-c2a9-434d-95c0-ab8153b19ee7.png)

**Comment by Claudiohbsantos** [comment]
Hey @pxladin ! Sorry about the scary notification. @eugabrielsilva  is correct, the difference is that the previous version only required access to github.com while now we also do the same with azure, gitea and bitbucket. 

You can see the manifest with the permissions from the previous version [here](https://github.com/Claudiohbsantos/github-material-icons-extension/blob/v1.5.1/src/manifest.json) and compare it with the current manifest permissions [here](https://github.com/Claudiohbsantos/github-material-icons-extension/blob/v1.6.1/src/manifest.json). 

If you click on "Show Details" on that notification you'll see the same list of websites:
![wCms8sI3V9](https://user-images.githubusercontent.com/11323215/176980181-f2cd40ed-d71e-4a2b-90f9-e07090c1b3d8.png)

Also good to note is that with the upcoming #41 and the potential for an options page where we can set a couple of options for the extension (such as icon size, icon pack, etc...) there will probably be a couple of other changes in permissions in the next couple of versions. I'll try to keep these to a minimum but unfortunately I don't know a better way to notify users of why permissions are being changed.

**Comment by pxladin** [comment]
@Claudiohbsantos Ah, that makes sense. Thank you for clearing that up.
