### ISSUE TITLE
Add option for file prefixes

### ISSUE THREAD

**Issue by fabianamhof** [Claudiohbsantos/github-material-icons-extension#48]
To have all of our files sorted by type we name them type.*.ts. It would be great if we could specify this pattern in the settings of the extension.

**Comment by Claudiohbsantos** [comment]
Hey @fabianamhof . I'm probably a couple of months too late, but in case this is still of interest, would you mind expanding on what the desired feature is here? Is the idea that you want to specify a custom icon based on the filename pattern?

**Comment by fabianamhof** [comment]
Hey @Claudiohbsantos. In my projects I prefer the naming `type.*.ts` over `*.type.ts.` For example `repository.user.ts,` `service.book.ts` and so on.
It would be great if I could specify that the first part of the filename (repository, service,...) gets used for selecting the icon.
