### ISSUE TITLE
Nightly build to the extension

### ISSUE THREAD

**Issue by shivapoudel** [Claudiohbsantos/github-material-icons-extension#5]
Seems like many icons are missing in the browser but present in the VSCode with the respective material theme. Please do update the addon and if possible can the extension be auto-updated with some schedule using GitHub actions.

**Comment by Claudiohbsantos** [comment]
You're right, looks like this is lagging 2 minor versions behind. I'll try to release an update tonight.

Last time I tried to automate the updates I couldn't find a good way to automate the release to the chrome store, which is the most time-consuming task of an update anyway. I'll check again to see if there are any new solutions around but please let me know if you know of any good workflows for that

**Comment by shivapoudel** [comment]
@Claudiohbsantos I have refactored the extension while studying the codebase yesterday night to develop for MS Edge. Can I submit the PR of those changes?

**Comment by shivapoudel** [comment]
@Claudiohbsantos Let add zip assets via CI for the MS Edge store so I can submit them manually for an update. When are we gonna release the next update of the extension?

If we can submit it this week then it will be better!

**Comment by Claudiohbsantos** [comment]
@shivapoudel I created a manual release until I finish the CD work: https://github.com/Claudiohbsantos/github-material-icons-extension/releases/tag/v1.4.0

I still have some hope of finishing the CD workflows this week, but I've ended up far busier than I expected so I thought it was safer to make a manual release just to get it out of the door already :)

**Comment by Claudiohbsantos** [comment]
I just pushed a first attempt at auto-updates to the chrome and firefox stores. The action will also cut a new release whenever a new upstream version is found.

https://github.com/Claudiohbsantos/github-material-icons-extension/commit/8aec94d59c4779d213fd7417d6ba0837b333aabd

I'll be monitoring it for a bit to make sure it actually works, but I'm closing this issue since this should address it :)
