### ISSUE TITLE
File chrome-extension://bggfcpfjbdkhfhfmkjpbhnkhnpjjeomc/file.svg is missing

### ISSUE THREAD

**Issue by AdamRaichu** [Claudiohbsantos/github-material-icons-extension#57]
When using `v1.7.8`, I opened the repo https://github.com/FabricMC/fabric/tree/1.19.4. The icon for the file called `HEADER` did not load. Apparently it was trying to reference the missing file `file.svg`.

**Comment by trits** [comment]
The same issue is also happening inside this repository apparently (last two files): 

![image](https://user-images.githubusercontent.com/10000498/231385688-61d327a3-8189-483d-ba33-dc4bff85c927.png)

**Comment by kidonng** [comment]
Seems lie the `file` icon is removed upstream in https://github.com/PKief/vscode-material-icon-theme/pull/1916/files#diff-317497a38df17a0275b60bac77f83ffd7c485cf26c979588490ab59ffdb9d329

**Comment by PKief** [comment]
Short update, the file.svg file will come back ;) So nothing to do on your side. I'll publish a new version of the npm package shortly which will contain the file.svg file again 👍

**Comment by Claudiohbsantos** [comment]
Thanks @PKief ! I had not noticed this until now so this issue just magically self resolved hahaha
