### ISSUE TITLE
components icon missing when icon pack is angular

### ISSUE THREAD

**Issue by vmuresanu** [Claudiohbsantos/github-material-icons-extension#58]
When icon pack is angular the components icon is crashing:
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/26407402/231751836-f0f82939-7f8d-4fcd-85a6-ea8c37010bcb.png">

However, if we select React / Vue or nest components icon seems to work.

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/26407402/231752198-ac4b0361-3d50-405f-83c9-8b0fe4e9b324.png">

**Comment by Claudiohbsantos** [comment]
yeah, something is not working properly there, I just managed to reproduce the issue. I'll see if there's something wrong with how we're pulling that icon pack

**Comment by Claudiohbsantos** [comment]
actually, the bug was simple enough that I am pretty sure I found the source already. I'm pushing a fix that will be included in the next version
![Screen Shot 2023-04-27 at 1 18 16 AM](https://user-images.githubusercontent.com/11323215/234766003-c991fa3d-d163-435e-b76b-268a55bbd7f7.png)
