### ISSUE TITLE
Duplicated Icons when changing icon Packs on 1.8.0

### ISSUE THREAD

**Issue by Claudiohbsantos** [Claudiohbsantos/github-material-icons-extension#63]
Just recording that I've noticed a small bug with the version that I just released where changing icon packs results in duplicated icons until refresh:
![Screen Shot 2023-04-27 at 12 51 19 AM](https://user-images.githubusercontent.com/11323215/234762725-aec5771c-f3c9-4ce1-8935-5d30c089387a.png)

Pretty sure this is just a side effect of some of the changes to the icon replacement logic we introduced in #56 . Overall I'd rather live with this for a bit than revert since a lot of people seem to be using the new code view.

@csandman just tagging you for visibility, I'm happy to take a stab at it .

**Comment by andry81** [comment]
Just for instance, there is another icons extension and it works as expected: https://github.com/homerchen19/github-file-icons

**Comment by csandman** [comment]
Ah, that's my bad for not checking the icon packs! It was a pretty simple fix though, and I just submitted a PR!
