### ISSUE TITLE
Add support for VSCode Dev

### ISSUE THREAD

**Issue by jamiehaywood** [Claudiohbsantos/github-material-icons-extension#70]
Raising a feature req. to add support for [VSCode Dev](https://vscode.dev/)

Have started work on it, and will raise a PR in due course :)

**Comment by csandman** [comment]
What's the advantage to using this package for it over just installing the Material Icon Theme in vscode.dev?

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/9214195/a6229741-968c-402a-9f0c-6d7f8cc77726)

**Comment by jamiehaywood** [comment]
because I have to reinstall it every time I open a repo through azure devops

**Comment by csandman** [comment]
Really? It seems to persist fine for me. How are you opening the repo?

**Comment by busybox11** [comment]
@jamiehaywood You can provide a list of extensions to automatically install as part of your .vscode / editorconfig

**Comment by AdamRaichu** [comment]
I believe [settings sync](https://code.visualstudio.com/docs/editor/settings-sync) lets you do that, you just need to enable it.

**Comment by jamiehaywood** [comment]
closing this because of @AdamRaichu 's valid workaround
