### ISSUE TITLE
File icons don't seem to be correctly indented

### ISSUE THREAD

**Issue by irfanmekic** [Claudiohbsantos/github-material-icons-extension#77]
While a minor cosmetic point, I find it a bit annoying that the structure of a folder looks like the below screenshot - 

![Screenshot 2023-11-16 at 11 48 56 AM](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/46060475/64e35aea-191d-4d5f-9138-5dfbc3d13cdd)

With the above, it looks like `sandbox.ipynb` is part of the `strategies\` folder, which isn't the case.

Rather, I think it would make more sense for the file to have the same indentation level as the 3 folders within `src/`, since they are all at the same level in that particular folder (where the red line is drawn in the below image) -

![Screenshot 2023-11-16 at 11 49 56 AM](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/46060475/cae7075f-be32-49a1-b47c-109bf11960ae)

This might already be feasible, I just haven't been able to figure it out if it is.

**Comment by csandman** [comment]
I'm not sure what this has to do with this extension, that is the default spacing for GitHub's code view:

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/9214195/f7d27f6e-e9c6-48f0-86e0-38d87ea7ecf9)

Also I disagree, the folder icon should line up with the file icons for everything at the same level, where as the chevron sticks out to the left. This is a common pattern across all file browsers and code editors.

MacOS Finder:

<img width="361" alt="image" src="https://github.com/Claudiohbsantos/github-material-icons-extension/assets/9214195/7a38d86c-6050-49ae-b8c4-d6239b4537f4">

VS Code:

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/9214195/bb4f1807-72f2-4b3c-af91-5ae0a02b081d)
