### ISSUE TITLE
Redux-store, redux-selector, redux-reducer, and redux-actions not display icon on VS code editer in mac

### ISSUE THREAD

**Issue by Bhavesh1236** [Claudiohbsantos/github-material-icons-extension#78]
in my case issue on
Material Icon Theme : v4.32.0 version 

![Screenshot 2023-12-28 at 11 43 43 AM](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/102301463/a9fd60df-6ec5-4d1c-a9e0-bdbd5a64f3ab)

**Comment by csandman** [comment]
I think you're looking for the project this project is based on: https://github.com/PKief/vscode-material-icon-theme

This repo is for a chrome extension haha
