### ISSUE TITLE
Dark/Light theme detection

### ISSUE THREAD

**Issue by Claudiohbsantos** [Claudiohbsantos/github-material-icons-extension#8]
Moving discussion from https://github.com/PKief/vscode-material-icon-theme/issues/1105 to here

**Comment by shivapoudel** [comment]
Fixed https://github.com/Claudiohbsantos/github-material-icons-extension/pull/7/commits/dec3b8827f23f906cbcdb98ecbb1022cc0109f01

**Comment by Claudiohbsantos** [comment]
Thanks! that's a great addition! 

At some point it would be great to make this toggleable since I think the github profile settings override the browser preference, so there might be mismatch there. It's already an improvement over what we have though so it should probably come in a separate PR if we ever get to it

**Comment by shivapoudel** [comment]
@Claudiohbsantos We can close this as we now support this feature!
